### PR TITLE
Add slsReceiver ctor overload

### PR DESCRIPTION
**Pull request by sdebionne**
I suggest to add a constructor overload of `slsReceiverUsers` (and `slsReceiver`) that takes the TCP/IP port in argument. IMHO, it is the responsibility of the application that uses the slsDetector libraries to parse the command line/config file and provide the argument.

Also I would recommend to use `std::unique_ptr<>` instead of raw pointers, see [Avoid calling new and delete explicitly](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly) for the rationale.

Tell me if I'm not targeting the right branch for these modifications!

### CODE REVIEW

**Comment by sdebionne** [comment]
`std::make_unique` is indeed C++14 (commented in the PR) and I did not know about `sls::make_unique`. Do you want me to patch it?

**Comment by erikfrojdh** [comment]
If you want to sure go ahead! Then I merge the pull request.

**Comment by sdebionne** [comment]
@erikfrojdh Here you go!

**Comment by thattil** [comment]
Sounds good. The overloaded function is a good idea. Thanks Samuel!

**Pull request merged**
